config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :tasks
  
  get 'home/about'
  root 'home#index'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :tasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index   
  end

  def about
    
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]
  # GET /tasks or /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1 or /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
   # @task = Task.new
   @task = current_user.tasks.build
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks or /tasks.json
  def create
    #@task = Task.new(task_params)
    @task = current_user.tasks.build(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to task_url(@task), notice: "Task was successfully created." }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1 or /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to task_url(@task), notice: "Task was successfully updated." }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1 or /tasks/1.json
  def destroy
    @task.destroy

    respond_to do |format|
      format.html { redirect_to tasks_url, notice: "Task was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @task = current_user.tasks.find_by(id: params[:id])
    redirect_to tasks_path, notice: "Not Authorized To Edit This Task" if @task.nil?
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def task_params
      params.require(:task).permit(:title, :description, :due_date, :priority, :completed, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/home/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-primary" data-bs-theme="dark">
  <div class="container-fluid">
    <%= link_to 'TMS', root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Home', root_path, class:"nav-link active" %>
        </li>
        <li class="nav-item">
          <%= link_to 'About', home_about_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Tasks', tasks_path, class:"nav-link" %>
        </li>
          <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to 'Add Task', new_task_path, class:"nav-link" %>
            </li>
            <li class="nav-item">
              <%= button_to 'Sign Out', destroy_user_session_path, method: :delete, class:"nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to 'Edit Profile', edit_user_registration_path, class:"nav-link" %>
            </li>  
          <% else %>
 
          <% end %>   
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-light" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<div class="container">
  <div class="container my-5">
  <div class="row justify-content-center">
    <div class="">
      <!-- Welcoming Card -->
      <div class="card shadow-md bg-white rounded">
        <div class="card-body text-center">
          <h1 class="display-4 text-primary mb-3">Task Management System</h1>
          <br>
          <h4 class="">Here is the github repository <a href="https://github.com/Naglis-M/TaskManagementSystem" class="link-success link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover">Link</a></h4>
          <br>
        </div>
      </div>     
    </div>
  </div>
  </div>
</div>

app/views/home/index.html.erb
<div class="container">
  <div class="container my-5">
  <div class="row justify-content-center">
    <div class="">
      <!-- Welcoming Card -->
      <div class="card shadow-md bg-white rounded">
        <div class="card-body text-center">
          <h1 class="display-4 text-primary mb-3">Welcome to the Task Management System</h1>
          <br>

          <br>


          <% if user_signed_in? %>
            <h4 class="">You're Signed In</h4>
            <h4 class="">Head over to the Tasks page</h4>
          <% else %>
          <!-- Buttons For Logging In Or Signing Up -->
            <h4 class="">To start managing your Tasks Login or Sign Up</h4>
            <br>
            <%= link_to 'Sign Up', new_user_registration_path, class:"btn btn-primary" %>
            <%= link_to 'Login', new_user_session_path, class:"btn btn-secondary" %>
          <% end %>
        </div>
      </div>     
    </div>
  </div>
  </div>
</div>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Task Management System</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= render 'home/navbar' %> 
    <div class="container">
      <br>
      <% if notice %>
        <%= render 'layouts/alerts' %>
      <% end %>

      <%= yield %>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with(model: task) do |form| %>
  <% if task.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
        <% task.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="container">
    <div class="container my-5">
    <div class="row justify-content-center">
      <div class="">
        <!-- Task Box -->
        <div class="card shadow-md w-75 text-bg-secondary mb-3">
          <div class="card-body">
              <div class="mb-3">
                <% form.label :title, style: "display: block" %>
                <%= form.text_field :title, class:"form-control", placeholder:"Task" %>
              </div>

              <div class="mb-3">
                <% form.label :description, style: "display: block" %>
                <%= form.text_area :description, class:"form-control", placeholder:"Description of the Task..."  %>
              </div>

              <div class="mb-3">
                <%= form.label :due_date, style: "display: block" %>
                <%= form.date_field :due_date, class:"form-control"%>
              </div>

              <div class="mb-3">
                <%= form.label :priority, style: "display: block" %>
                <%= form.number_field :priority, class:"form-control"%>
              </div>

              <div class="mb-3">
                <%= form.label :completed, style: "display: block" %>
                <%= form.check_box :completed, class:"form-check-input"%>
              </div>

              <div class="mb-3">
                <%= form.number_field :user_id, id: :task_user_id, class:"form-control", value:current_user.id, type: :hidden%>
              </div>

              <div class="actions">
                <%= form.submit class:"btn btn-primary" %>
              </div>
<% end %>

          </div>
        </div>     
      </div>
    </div>
    </div>
  </div>

app/views/tasks/_task.html.erb
<div id="<%= dom_id task %>">
  <p>
    <strong>Title:</strong>
    <%= task.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= task.description %>
  </p>

  <p>
    <strong>Due date:</strong>
    <%= task.due_date %>
  </p>

  <p>
    <strong>Priority:</strong>
    <%= task.priority %>
  </p>

  <p>
    <strong>Completed:</strong>
    <%= task.completed %>
  </p>

</div>

app/views/tasks/edit.html.erb
<br>
<h1>Editing Task: <%= @task.title %></h1>

<%= render "form", task: @task %>

<div>
  <%= link_to "Show this task", @task, class:"btn btn-outline-primary" %>
  <%= link_to "Back to Tasks", tasks_path, class:"btn btn-outline-secondary" %>
</div>

app/views/tasks/index.html.erb
<h1>Tasks</h1>
<table class="table table-striped table-bordered table-hover">
  <thead class="table-dark">
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Due Date</th>
      <th>Priority</th>
      <th>Completed?</th>
      <th colspan="3"></th>

    </tr>
  </thead>

  <tbody>
      <% @tasks.each do |task| %>
        <% if task.user == current_user %>
          <tr>
            <td><%= task.title %></td>
            <td><%= task.description %></td>
            <td><%= task.due_date %></td>
            <td><%= task.priority %></td>
            <td><%= task.completed %></td>
            <td><%= link_to "Show", task, class:"btn btn-primary btn-sm"  %></td>
            <td><%= link_to "Edit", edit_task_path(task), class:"btn btn-warning btn-sm"  %></td>
            <td><%= button_to 'Delete', task_path(task), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm' %></td>
          </tr>
        <% end %>
      <% end %>
  </tbody>  
</table>

<br>

<%= link_to "New task", new_task_path, class:"btn btn-secondary" %>

app/views/tasks/new.html.erb
<h1>Add New task</h1>
<br>
<%= render "form", task: @task %>
<div>
  <%= link_to "Back to Tasks", tasks_path, class:"btn btn-outline-secondary" %>
</div>

app/views/tasks/show.html.erb
<div class="container">
  <div class="container my-5">
  <div class="row justify-content-center">
    <div class="">
      <!-- Task Box -->
      <div class="card shadow-md w-75 text-bg-secondary mb-3">
        <div class="card-header"><%= @task.title %></div>
        <div class="card-body">
          <p class="lead">Description: <%= @task.description %></p>
          <p class="lead">Due Date: <%= @task.due_date %></p>
          <p class="lead">Priority: <%= @task.priority %></p>
          <p class="lead">Completed: <%= @task.completed %></p>

          <br/>
          <!-- Buttons For Editing The Task Or Returning To All Tasks -->
          <%= link_to "Edit this task", edit_task_path(@task), class:"btn btn-warning"  %>
          <%= link_to "Back to Tasks", tasks_path, class:"btn btn-light"  %>

        </div>
      </div>     
    </div>
  </div>
  </div>
</div>